version: '2'

services:
  minio:
    image: minio/minio
    ports:
      - "13666:13666"
      - "13667:13667"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minioPassword
    command: server --console-address ":13667" --address ":13666" /data

volumes:
  minio_storage: {}